apiVersion: quickops.sand.tech/v1
kind: FullStackDeploy
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-operator-video-conference
    app.kubernetes.io/managed-by: kustomize
  name: fullstackdeploy-sample
  namespace: ingress-nginx
  # namespace: ingress-nginx
spec:
  frontendImage: "aasourav/aes-meal:0.85"
  frontendPort: 80
  frontendReplica: 3
  backendImage: "aasourav/aes-meal-server:0.29"
  backendPort: 8080
  backendReplica: 2
  backendEnv:
    "MONGO_URI": "mongodb://admin:password@172.17.18.250:27017/logs?authSource=admin"
    "MODE": "release"
    "MONGO_DATABASE": "logs"
