apiVersion: quickops.sand.tech/v1
kind: FullStackDeploy
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-operator-video-conference
    app.kubernetes.io/managed-by: kustomize
  name: fullstackdeploy-sample
  namespace: aas-ns
  # namespace: ingress-nginx
spec:
  frontendImage: "aasourav/aes-meal:0.85"
  frontendPort: 80
  frontendReplica: 3
  backendImage: "aasourav/aes-meal-server:0.29"
  backendPort: 8080
  backendReplica: 2
  backendEnv:
    "MONGO_URI": "mongodb+srv://aesmeal:aesmeal@aes-meal.nzl6b.mongodb.net/aesmeal?retryWrites=true&w=majority&appName=aes-meal"
    "MODE": "release"
    "MONGO_DATABASE": "aesmeal"
